/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rpc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rpc.pb-c.h"
void   proto__trace_info__init
                     (Proto__TraceInfo         *message)
{
  static const Proto__TraceInfo init_value = PROTO__TRACE_INFO__INIT;
  *message = init_value;
}
size_t proto__trace_info__get_packed_size
                     (const Proto__TraceInfo *message)
{
  assert(message->base.descriptor == &proto__trace_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__trace_info__pack
                     (const Proto__TraceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__trace_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__trace_info__pack_to_buffer
                     (const Proto__TraceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__trace_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TraceInfo *
       proto__trace_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TraceInfo *)
     protobuf_c_message_unpack (&proto__trace_info__descriptor,
                                allocator, len, data);
}
void   proto__trace_info__free_unpacked
                     (Proto__TraceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__trace_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__rpcrequest__init
                     (Proto__RPCRequest         *message)
{
  static const Proto__RPCRequest init_value = PROTO__RPCREQUEST__INIT;
  *message = init_value;
}
size_t proto__rpcrequest__get_packed_size
                     (const Proto__RPCRequest *message)
{
  assert(message->base.descriptor == &proto__rpcrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__rpcrequest__pack
                     (const Proto__RPCRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__rpcrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__rpcrequest__pack_to_buffer
                     (const Proto__RPCRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__rpcrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__RPCRequest *
       proto__rpcrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__RPCRequest *)
     protobuf_c_message_unpack (&proto__rpcrequest__descriptor,
                                allocator, len, data);
}
void   proto__rpcrequest__free_unpacked
                     (Proto__RPCRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__rpcrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__rpcresponse__init
                     (Proto__RPCResponse         *message)
{
  static const Proto__RPCResponse init_value = PROTO__RPCRESPONSE__INIT;
  *message = init_value;
}
size_t proto__rpcresponse__get_packed_size
                     (const Proto__RPCResponse *message)
{
  assert(message->base.descriptor == &proto__rpcresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__rpcresponse__pack
                     (const Proto__RPCResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__rpcresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__rpcresponse__pack_to_buffer
                     (const Proto__RPCResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__rpcresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__RPCResponse *
       proto__rpcresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__RPCResponse *)
     protobuf_c_message_unpack (&proto__rpcresponse__descriptor,
                                allocator, len, data);
}
void   proto__rpcresponse__free_unpacked
                     (Proto__RPCResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__rpcresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__trace_info__field_descriptors[7] =
{
  {
    "received_time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TraceInfo, received_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replied_time",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TraceInfo, replied_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "machine_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TraceInfo, machine_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endpoint_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TraceInfo, endpoint_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TraceInfo, error_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "redirect",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TraceInfo, redirect),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "child_calls",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TraceInfo, n_child_calls),
    offsetof(Proto__TraceInfo, child_calls),
    &proto__trace_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__trace_info__field_indices_by_name[] = {
  6,   /* field[6] = child_calls */
  3,   /* field[3] = endpoint_name */
  4,   /* field[4] = error_message */
  2,   /* field[2] = machine_name */
  0,   /* field[0] = received_time */
  5,   /* field[5] = redirect */
  1,   /* field[1] = replied_time */
};
static const ProtobufCIntRange proto__trace_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor proto__trace_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TraceInfo",
  "TraceInfo",
  "Proto__TraceInfo",
  "proto",
  sizeof(Proto__TraceInfo),
  7,
  proto__trace_info__field_descriptors,
  proto__trace_info__field_indices_by_name,
  1,  proto__trace_info__number_ranges,
  (ProtobufCMessageInit) proto__trace_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__rpcrequest__field_descriptors[7] =
{
  {
    "rpc_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCRequest, rpc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srvc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCRequest, srvc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "procedure",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCRequest, procedure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deadline",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Proto__RPCRequest, has_deadline),
    offsetof(Proto__RPCRequest, deadline),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "caller_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCRequest, caller_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "want_trace",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Proto__RPCRequest, has_want_trace),
    offsetof(Proto__RPCRequest, want_trace),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__rpcrequest__field_indices_by_name[] = {
  5,   /* field[5] = caller_id */
  3,   /* field[3] = data */
  4,   /* field[4] = deadline */
  2,   /* field[2] = procedure */
  0,   /* field[0] = rpc_id */
  1,   /* field[1] = srvc */
  6,   /* field[6] = want_trace */
};
static const ProtobufCIntRange proto__rpcrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor proto__rpcrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.RPCRequest",
  "RPCRequest",
  "Proto__RPCRequest",
  "proto",
  sizeof(Proto__RPCRequest),
  7,
  proto__rpcrequest__field_descriptors,
  proto__rpcrequest__field_indices_by_name,
  1,  proto__rpcrequest__number_ranges,
  (ProtobufCMessageInit) proto__rpcrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue proto__rpcresponse__status__enum_values_by_number[13] =
{
  { "STATUS_UNKNOWN", "PROTO__RPCRESPONSE__STATUS__STATUS_UNKNOWN", 0 },
  { "STATUS_OK", "PROTO__RPCRESPONSE__STATUS__STATUS_OK", 1 },
  { "STATUS_NOT_FOUND", "PROTO__RPCRESPONSE__STATUS__STATUS_NOT_FOUND", 2 },
  { "STATUS_NOT_OK", "PROTO__RPCRESPONSE__STATUS__STATUS_NOT_OK", 4 },
  { "STATUS_SERVER_ERROR", "PROTO__RPCRESPONSE__STATUS__STATUS_SERVER_ERROR", 5 },
  { "STATUS_TIMEOUT", "PROTO__RPCRESPONSE__STATUS__STATUS_TIMEOUT", 6 },
  { "STATUS_OVERLOADED_RETRY", "PROTO__RPCRESPONSE__STATUS__STATUS_OVERLOADED_RETRY", 7 },
  { "STATUS_CLIENT_REQUEST_ERROR", "PROTO__RPCRESPONSE__STATUS__STATUS_CLIENT_REQUEST_ERROR", 9 },
  { "STATUS_CLIENT_NETWORK_ERROR", "PROTO__RPCRESPONSE__STATUS__STATUS_CLIENT_NETWORK_ERROR", 10 },
  { "STATUS_CLIENT_CALLED_WRONG", "PROTO__RPCRESPONSE__STATUS__STATUS_CLIENT_CALLED_WRONG", 11 },
  { "STATUS_MISSED_DEADLINE", "PROTO__RPCRESPONSE__STATUS__STATUS_MISSED_DEADLINE", 12 },
  { "STATUS_LOADSHED", "PROTO__RPCRESPONSE__STATUS__STATUS_LOADSHED", 13 },
  { "STATUS_UNHEALTHY", "PROTO__RPCRESPONSE__STATUS__STATUS_UNHEALTHY", 14 },
};
static const ProtobufCIntRange proto__rpcresponse__status__value_ranges[] = {
{0, 0},{4, 3},{9, 7},{0, 13}
};
static const ProtobufCEnumValueIndex proto__rpcresponse__status__enum_values_by_name[13] =
{
  { "STATUS_CLIENT_CALLED_WRONG", 9 },
  { "STATUS_CLIENT_NETWORK_ERROR", 8 },
  { "STATUS_CLIENT_REQUEST_ERROR", 7 },
  { "STATUS_LOADSHED", 11 },
  { "STATUS_MISSED_DEADLINE", 10 },
  { "STATUS_NOT_FOUND", 2 },
  { "STATUS_NOT_OK", 3 },
  { "STATUS_OK", 1 },
  { "STATUS_OVERLOADED_RETRY", 6 },
  { "STATUS_SERVER_ERROR", 4 },
  { "STATUS_TIMEOUT", 5 },
  { "STATUS_UNHEALTHY", 12 },
  { "STATUS_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor proto__rpcresponse__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.RPCResponse.Status",
  "Status",
  "Proto__RPCResponse__Status",
  "proto",
  13,
  proto__rpcresponse__status__enum_values_by_number,
  13,
  proto__rpcresponse__status__enum_values_by_name,
  3,
  proto__rpcresponse__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor proto__rpcresponse__field_descriptors[5] =
{
  {
    "rpc_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCResponse, rpc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Proto__RPCResponse, has_response_data),
    offsetof(Proto__RPCResponse, response_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCResponse, response_status),
    &proto__rpcresponse__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCResponse, error_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "traceinfo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__RPCResponse, traceinfo),
    &proto__trace_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__rpcresponse__field_indices_by_name[] = {
  3,   /* field[3] = error_message */
  1,   /* field[1] = response_data */
  2,   /* field[2] = response_status */
  0,   /* field[0] = rpc_id */
  4,   /* field[4] = traceinfo */
};
static const ProtobufCIntRange proto__rpcresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor proto__rpcresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.RPCResponse",
  "RPCResponse",
  "Proto__RPCResponse",
  "proto",
  sizeof(Proto__RPCResponse),
  5,
  proto__rpcresponse__field_descriptors,
  proto__rpcresponse__field_indices_by_name,
  1,  proto__rpcresponse__number_ranges,
  (ProtobufCMessageInit) proto__rpcresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
